export default [
  [ {code: "Backquote", en: "`", upperEn: "~", ru: "ё"},
    {code: "Digit1", en: "1", upperEn: "!"},
    {code: "Digit2", en: "2", upperEn: "@", upperRu: '"'},
    {code: "Digit3", en: "3", upperEn: "#", upperRu: "№"},
    {code: "Digit4", en: "4", upperEn: "$", upperRu: ";"},
    {code: "Digit5", en: "5", upperEn: "%"},
    {code: "Digit6", en: "6", upperEn: "^", upperRu: ":"},
    {code: "Digit7", en: "7", upperEn: "&", upperRu: "?"},
    {code: "Digit8", en: "8", upperEn: "*"},
    {code: "Digit9", en: "9", upperEn: "("},
    {code: "Digit0", en: "0", upperEn: ")"},
    {code: "Minus", en: "-", upperEn: "_"},
    {code: "Equal", en: "=", upperEn: "+"},
    {code: "Backspace", func: "Backspace"} ], 
  [ {code: "Tab", func: "Tab"},
    {code: "KeyQ", en: "q", ru: "й"},
    {code: "KeyW", en: "w", ru: "ц"},
    {code: "KeyE", en: "e", ru: "у"},
    {code: "KeyR", en: "r", ru: "к"},
    {code: "KeyT", en: "t", ru: "е"},
    {code: "KeyY", en: "y", ru: "н"},
    {code: "KeyU", en: "u", ru: "г"},
    {code: "KeyI", en: "i", ru: "ш"},
    {code: "KeyO", en: "o", ru: "щ"},
    {code: "KeyP", en: "p", ru: "з"},
    {code: "BracketLeft", en: "[", upperEn: "{", ru: "х"},
    {code: "BracketRight", en: "]", upperEn: "}", ru: "ъ"},
    {code: "Backslash", en: "\\", upperEn: "|", upperRu: "/"},
    {code: "Delete", func: "Del" } ],
  [ {code: "CapsLock", func: "CapsLock"},
    {code: "KeyA", en: "a", ru: "ф"},
    {code: "KeyS", en: "s", ru: "ы"},
    {code: "KeyD", en: "d", ru: "в"},
    {code: "KeyF", en: "f", ru: "а"},
    {code: "KeyG", en: "g", ru: "п"},
    {code: "KeyH", en: "h", ru: "р"},
    {code: "KeyJ", en: "j", ru: "о"},
    {code: "KeyK", en: "k", ru: "л"},
    {code: "KeyL", en: "l", ru: "д"},
    {code: "Semicolon", en: ";", upperEn: ":", ru: "ж"},
    {code: "Quote", en: "'", upperEn: '"', ru: "э"},
    {code: "Enter", func: "Enter" } ],
  [ {code: "ShiftLeft", func: "Shift"},
    {code: "KeyZ", en: "z", ru: "я"},
    {code: "KeyX", en: "x", ru: "ч"},
    {code: "KeyC", en: "c", ru: "с"},
    {code: "KeyV", en: "v", ru: "м"},
    {code: "KeyB", en: "b", ru: "и"},
    {code: "KeyN", en: "n", ru: "т"},
    {code: "KeyM", en: "m", ru: "ь"},
    {code: "Comma", en: ",", upperEn: "<", ru: "б"},
    {code: "Period", en: ".", upperEn: ">", ru: "ю"},
    {code: "Slash", en: "/", upperEn: "?", ru: ".", upperRu: ","},
    {code: "ArrowUp", en: "↑"},
    {code: "ShiftRight", func: "Shift" } ], 
  [ {code: "ControlLeft", func: "Ctrl"},
    {code: "MetaLeft", func: "Win"},
    {code: "AltLeft", func: "Alt"},
    {code: "Space", en: " "},
    {code: "AltRight", func: "Alt"},
    {code: "ArrowLeft", en: "←"},
    {code: "ArrowDown", en: "↓"},
    {code: "ArrowRight", en: "→"},
    {code: "ControlRight", func: "Ctrl" } ]
  ]
  